const mongoose = require('mongoose');
require('dotenv').config();

// User Schema
const userSchema = new mongoose.Schema({
  userId: { type: String, required: true, unique: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  email: { type: String, required: true, unique: true },
  phone: { type: String, required: true },
  dateOfBirth: { type: Date, required: true },
  gender: { type: String, required: true, enum: ['Male', 'Female', 'Other'] },
  address: { type: String, required: true },
  city: { type: String, required: true },
  state: { type: String, required: true },
  country: { type: String, required: true },
  zipCode: { type: String, required: true },
  occupation: { type: String, required: true },
  company: { type: String, required: true },
  department: { type: String, required: true },
  jobTitle: { type: String, required: true },
  employeeId: { type: String, required: true, unique: true },
  joinDate: { type: Date, required: true },
  salary: { type: Number, required: true },
  workType: { type: String, required: true, enum: ['Full-time', 'Part-time', 'Contract', 'Intern'] },
  status: { type: String, required: true, enum: ['Active', 'Inactive', 'On Leave', 'Terminated'] },
  skills: { type: String, required: true },
  experience: { type: Number, required: true },
  education: { type: String, required: true },
  certifications: { type: String, required: true },
  emergencyContact: { type: String, required: true },
  emergencyPhone: { type: String, required: true },
  relationship: { type: String, required: true },
  bloodGroup: { type: String, required: true },
  maritalStatus: { type: String, required: true, enum: ['Single', 'Married', 'Divorced', 'Widowed'] },
  nationality: { type: String, required: true },
  languages: { type: String, required: true },
  hobbies: { type: String, required: true },
  socialMedia: { type: String, required: true },
  notes: { type: String, required: true },
  priority: { type: String, required: true, enum: ['Low', 'Medium', 'High'] },
  assignedTo: { type: String, required: true },
  dateAdded: { type: Date, default: Date.now }
}, {
  timestamps: true
});

const User = mongoose.model('User', userSchema);

const sampleUsers = [
  {
    userId: 'USR0001',
    firstName: 'Rajesh',
    lastName: 'Kumar',
    email: 'rajesh.kumar@techcorp.com',
    phone: '+91-9876543210',
    dateOfBirth: new Date('1990-05-15'),
    gender: 'Male',
    address: '123, Park Avenue, MG Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560001',
    occupation: 'Software Engineer',
    company: 'TechCorp Solutions',
    department: 'Engineering',
    jobTitle: 'Senior Software Engineer',
    employeeId: 'TC001',
    joinDate: new Date('2024-01-15'),
    salary: 1200000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'JavaScript, React, Node.js, MongoDB, Python',
    experience: 6,
    education: 'B.Tech Computer Science',
    certifications: 'AWS Certified Developer, Google Cloud Professional',
    emergencyContact: 'Sunita Kumar',
    emergencyPhone: '+91-9876543211',
    relationship: 'Spouse',
    bloodGroup: 'B+',
    maritalStatus: 'Married',
    nationality: 'Indian',
    languages: 'English, Hindi, Kannada',
    hobbies: 'Reading, Coding, Traveling',
    socialMedia: 'linkedin.com/in/rajeshkumar, github.com/rajeshkumar',
    notes: 'Excellent team player with strong technical skills',
    priority: 'High',
    assignedTo: 'Manager A',
    dateAdded: new Date('2024-01-15')
  },
  {
    userId: 'USR0002',
    firstName: 'Priya',
    lastName: 'Sharma',
    email: 'priya.sharma@techcorp.com',
    phone: '+91-9876543212',
    dateOfBirth: new Date('1992-08-22'),
    gender: 'Female',
    address: '456, Residency Road, Indiranagar',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560038',
    occupation: 'Product Manager',
    company: 'TechCorp Solutions',
    department: 'Product',
    jobTitle: 'Product Manager',
    employeeId: 'TC002',
    joinDate: new Date('2023-06-10'),
    salary: 1500000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Product Strategy, Agile, Scrum, Data Analysis, UX Design',
    experience: 5,
    education: 'MBA Marketing',
    certifications: 'PMP Certified, Scrum Master',
    emergencyContact: 'Ramesh Sharma',
    emergencyPhone: '+91-9876543213',
    relationship: 'Father',
    bloodGroup: 'A+',
    maritalStatus: 'Single',
    nationality: 'Indian',
    languages: 'English, Hindi, Tamil',
    hobbies: 'Yoga, Painting, Reading',
    socialMedia: 'linkedin.com/in/priyasharma',
    notes: 'Strong product vision and leadership skills',
    priority: 'High',
    assignedTo: 'Manager B',
    dateAdded: new Date('2023-06-10')
  },
  {
    userId: 'USR0003',
    firstName: 'Amit',
    lastName: 'Patel',
    email: 'amit.patel@techcorp.com',
    phone: '+91-9876543214',
    dateOfBirth: new Date('1988-12-10'),
    gender: 'Male',
    address: '789, Commercial Street, Brigade Road',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560025',
    occupation: 'DevOps Engineer',
    company: 'TechCorp Solutions',
    department: 'Infrastructure',
    jobTitle: 'DevOps Lead',
    employeeId: 'TC003',
    joinDate: new Date('2022-03-20'),
    salary: 1400000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Docker, Kubernetes, AWS, Azure, CI/CD, Terraform',
    experience: 8,
    education: 'B.E Computer Science',
    certifications: 'AWS DevOps Engineer, Kubernetes Administrator',
    emergencyContact: 'Rekha Patel',
    emergencyPhone: '+91-9876543215',
    relationship: 'Spouse',
    bloodGroup: 'O+',
    maritalStatus: 'Married',
    nationality: 'Indian',
    languages: 'English, Hindi, Gujarati',
    hobbies: 'Gaming, Trekking, Photography',
    socialMedia: 'linkedin.com/in/amitpatel, github.com/amitpatel',
    notes: 'Infrastructure expert with cloud specialization',
    priority: 'Medium',
    assignedTo: 'Manager C',
    dateAdded: new Date('2022-03-20')
  },
  {
    userId: 'USR0004',
    firstName: 'Neha',
    lastName: 'Gupta',
    email: 'neha.gupta@techcorp.com',
    phone: '+91-9876543216',
    dateOfBirth: new Date('1993-04-18'),
    gender: 'Female',
    address: '321, Koramangala 5th Block',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560095',
    occupation: 'UX Designer',
    company: 'TechCorp Solutions',
    department: 'Design',
    jobTitle: 'Senior UX Designer',
    employeeId: 'TC004',
    joinDate: new Date('2023-09-05'),
    salary: 900000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Figma, Adobe XD, Sketch, User Research, Prototyping',
    experience: 4,
    education: 'B.Des Visual Communication',
    certifications: 'Google UX Design Certificate',
    emergencyContact: 'Anil Gupta',
    emergencyPhone: '+91-9876543217',
    relationship: 'Brother',
    bloodGroup: 'AB+',
    maritalStatus: 'Single',
    nationality: 'Indian',
    languages: 'English, Hindi, Bengali',
    hobbies: 'Sketching, Music, Travel',
    socialMedia: 'linkedin.com/in/nehagupta, behance.net/nehagupta',
    notes: 'Creative designer with user-centric approach',
    priority: 'Medium',
    assignedTo: 'Manager D',
    dateAdded: new Date('2023-09-05')
  },
  {
    userId: 'USR0005',
    firstName: 'Vikram',
    lastName: 'Singh',
    email: 'vikram.singh@techcorp.com',
    phone: '+91-9876543218',
    dateOfBirth: new Date('1987-07-25'),
    gender: 'Male',
    address: '654, HSR Layout, Sector 2',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560102',
    occupation: 'Data Scientist',
    company: 'TechCorp Solutions',
    department: 'Data Science',
    jobTitle: 'Senior Data Scientist',
    employeeId: 'TC005',
    joinDate: new Date('2021-11-15'),
    salary: 1600000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Python, Machine Learning, Deep Learning, NLP, TensorFlow',
    experience: 7,
    education: 'M.Sc Statistics',
    certifications: 'TensorFlow Developer Certificate',
    emergencyContact: 'Meena Singh',
    emergencyPhone: '+91-9876543219',
    relationship: 'Mother',
    bloodGroup: 'B+',
    maritalStatus: 'Married',
    nationality: 'Indian',
    languages: 'English, Hindi, Punjabi',
    hobbies: 'Chess, Reading, Research',
    socialMedia: 'linkedin.com/in/vikramsingh, kaggle.com/vikramsingh',
    notes: 'Data expert with ML specialization',
    priority: 'High',
    assignedTo: 'Manager E',
    dateAdded: new Date('2021-11-15')
  },
  {
    userId: 'USR0006',
    firstName: 'Anjali',
    lastName: 'Reddy',
    email: 'anjali.reddy@techcorp.com',
    phone: '+91-9876543220',
    dateOfBirth: new Date('1991-10-30'),
    gender: 'Female',
    address: '987, Whitefield, EPIP Zone',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560066',
    occupation: 'QA Engineer',
    company: 'TechCorp Solutions',
    department: 'Quality Assurance',
    jobTitle: 'QA Lead',
    employeeId: 'TC006',
    joinDate: new Date('2022-08-10'),
    salary: 1100000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Selenium, Cypress, JIRA, Test Planning, Automation',
    experience: 5,
    education: 'B.Tech Information Technology',
    certifications: 'ISTQB Foundation Level',
    emergencyContact: 'Ravi Reddy',
    emergencyPhone: '+91-9876543221',
    relationship: 'Brother',
    bloodGroup: 'A+',
    maritalStatus: 'Single',
    nationality: 'Indian',
    languages: 'English, Hindi, Telugu',
    hobbies: 'Cooking, Gardening, Music',
    socialMedia: 'linkedin.com/in/anjalireddy',
    notes: 'Quality assurance expert with automation skills',
    priority: 'Medium',
    assignedTo: 'Manager F',
    dateAdded: new Date('2022-08-10')
  },
  {
    userId: 'USR0007',
    firstName: 'Rohit',
    lastName: 'Verma',
    email: 'rohit.verma@techcorp.com',
    phone: '+91-9876543222',
    dateOfBirth: new Date('1989-03-12'),
    gender: 'Male',
    address: '147, Electronic City, Phase 1',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560100',
    occupation: 'Mobile Developer',
    company: 'TechCorp Solutions',
    department: 'Mobile',
    jobTitle: 'Senior Mobile Developer',
    employeeId: 'TC007',
    joinDate: new Date('2023-02-28'),
    salary: 1300000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'React Native, Flutter, Swift, Kotlin, iOS, Android',
    experience: 6,
    education: 'B.Tech Computer Science',
    certifications: 'React Native Certification',
    emergencyContact: 'Sunita Verma',
    emergencyPhone: '+91-9876543223',
    relationship: 'Mother',
    bloodGroup: 'O+',
    maritalStatus: 'Single',
    nationality: 'Indian',
    languages: 'English, Hindi, Marathi',
    hobbies: 'Mobile Development, Gaming, Fitness',
    socialMedia: 'linkedin.com/in/rohitverma, github.com/rohitverma',
    notes: 'Mobile development expert with cross-platform skills',
    priority: 'Medium',
    assignedTo: 'Manager G',
    dateAdded: new Date('2023-02-28')
  },
  {
    userId: 'USR0008',
    firstName: 'Kavita',
    lastName: 'Nair',
    email: 'kavita.nair@techcorp.com',
    phone: '+91-9876543224',
    dateOfBirth: new Date('1990-09-08'),
    gender: 'Female',
    address: '258, Jayanagar 4th Block',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560041',
    occupation: 'HR Manager',
    company: 'TechCorp Solutions',
    department: 'Human Resources',
    jobTitle: 'HR Manager',
    employeeId: 'TC008',
    joinDate: new Date('2021-05-20'),
    salary: 1000000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Recruitment, Employee Relations, Performance Management, HRIS',
    experience: 7,
    education: 'MBA HR',
    certifications: 'SHRM Certified Professional',
    emergencyContact: 'Nair N. Kumar',
    emergencyPhone: '+91-9876543225',
    relationship: 'Father',
    bloodGroup: 'B+',
    maritalStatus: 'Married',
    nationality: 'Indian',
    languages: 'English, Hindi, Malayalam',
    hobbies: 'Reading, Music, Social Work',
    socialMedia: 'linkedin.com/in/kavitanair',
    notes: 'HR professional with strong people management skills',
    priority: 'Low',
    assignedTo: 'Manager H',
    dateAdded: new Date('2021-05-20')
  },
  {
    userId: 'USR0009',
    firstName: 'Arjun',
    lastName: 'Mehta',
    email: 'arjun.mehta@techcorp.com',
    phone: '+91-9876543226',
    dateOfBirth: new Date('1992-11-22'),
    gender: 'Male',
    address: '369, Malleshwaram',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560003',
    occupation: 'Backend Developer',
    company: 'TechCorp Solutions',
    department: 'Engineering',
    jobTitle: 'Backend Developer',
    employeeId: 'TC009',
    joinDate: new Date('2023-07-15'),
    salary: 1050000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Java, Spring Boot, Microservices, PostgreSQL, Redis',
    experience: 4,
    education: 'B.E Computer Science',
    certifications: 'Oracle Java Certification',
    emergencyContact: 'Mehta S. Mehta',
    emergencyPhone: '+91-9876543227',
    relationship: 'Father',
    bloodGroup: 'A+',
    maritalStatus: 'Single',
    nationality: 'Indian',
    languages: 'English, Hindi, Gujarati',
    hobbies: 'Coding, Cricket, Movies',
    socialMedia: 'linkedin.com/in/arjunmehta, github.com/arjunmehta',
    notes: 'Backend developer with Java expertise',
    priority: 'Medium',
    assignedTo: 'Manager I',
    dateAdded: new Date('2023-07-15')
  },
  {
    userId: 'USR0010',
    firstName: 'Divya',
    lastName: 'Krishnan',
    email: 'divya.krishnan@techcorp.com',
    phone: '+91-9876543228',
    dateOfBirth: new Date('1993-06-15'),
    gender: 'Female',
    address: '741, BTM Layout 2nd Stage',
    city: 'Bangalore',
    state: 'Karnataka',
    country: 'India',
    zipCode: '560076',
    occupation: 'Marketing Manager',
    company: 'TechCorp Solutions',
    department: 'Marketing',
    jobTitle: 'Marketing Manager',
    employeeId: 'TC010',
    joinDate: new Date('2022-12-01'),
    salary: 1150000,
    workType: 'Full-time',
    status: 'Active',
    skills: 'Digital Marketing, SEO, SEM, Content Marketing, Analytics',
    experience: 5,
    education: 'MBA Marketing',
    certifications: 'Google Ads Certification',
    emergencyContact: 'Krishnan R. Krishnan',
    emergencyPhone: '+91-9876543229',
    relationship: 'Father',
    bloodGroup: 'O+',
    maritalStatus: 'Single',
    nationality: 'Indian',
    languages: 'English, Hindi, Tamil, Malayalam',
    hobbies: 'Writing, Traveling, Photography',
    socialMedia: 'linkedin.com/in/divyakrishnan',
    notes: 'Marketing professional with digital expertise',
    priority: 'Medium',
    assignedTo: 'Manager J',
    dateAdded: new Date('2022-12-01')
  }
];

// Generate 40 more users with varied data
const generateMoreUsers = () => {
  const firstNames = ['Rahul', 'Sneha', 'Karan', 'Pooja', 'Aditya', 'Swati', 'Manish', 'Rashmi', 'Vivek', 'Anita', 'Rohit', 'Kavita', 'Amit', 'Nisha', 'Vikas', 'Priyanka', 'Suresh', 'Meena', 'Deepak', 'Sonam', 'Rajat', 'Kirti', 'Mohan', 'Rashmi', 'Alok', 'Preeti', 'Naveen', 'Anjali', 'Ravi', 'Shweta'];
  const lastNames = ['Sharma', 'Gupta', 'Kumar', 'Singh', 'Patel', 'Reddy', 'Nair', 'Mehta', 'Jain', 'Agarwal', 'Yadav', 'Iyer', 'Pillai', 'Menon', 'Desai', 'Kulkarni', 'Joshi', 'Pandey', 'Mishra', 'Chatterjee'];
  const departments = ['Engineering', 'Sales', 'Marketing', 'HR', 'Finance', 'Operations', 'Customer Support', 'Admin', 'Legal', 'R&D'];
  const jobTitles = ['Developer', 'Manager', 'Analyst', 'Executive', 'Specialist', 'Coordinator', 'Associate', 'Lead', 'Consultant', 'Assistant'];
  const cities = ['Bangalore', 'Mumbai', 'Delhi', 'Hyderabad', 'Chennai', 'Pune', 'Kolkata', 'Ahmedabad'];
  const states = ['Karnataka', 'Maharashtra', 'Delhi', 'Telangana', 'Tamil Nadu', 'Maharashtra', 'West Bengal', 'Gujarat'];
  
  const moreUsers = [];
  for (let i = 11; i <= 50; i++) {
    const firstName = firstNames[Math.floor(Math.random() * firstNames.length)];
    const lastName = lastNames[Math.floor(Math.random() * lastNames.length)];
    const cityIndex = Math.floor(Math.random() * cities.length);
    
    moreUsers.push({
      userId: `USR${String(i).padStart(4, '0')}`,
      firstName,
      lastName,
      email: `${firstName.toLowerCase()}.${lastName.toLowerCase()}@techcorp.com`,
      phone: `+91-987654${String(3230 + i).padStart(4, '0')}`,
      dateOfBirth: new Date(1985 + Math.floor(Math.random() * 15), Math.floor(Math.random() * 12), Math.floor(Math.random() * 28) + 1),
      gender: ['Male', 'Female'][Math.floor(Math.random() * 2)],
      address: `${Math.floor(Math.random() * 999) + 1}, ${['Main Street', 'Park Road', 'MG Road', 'Commercial Street'][Math.floor(Math.random() * 4)]}`,
      city: cities[cityIndex],
      state: states[cityIndex],
      country: 'India',
      zipCode: String(Math.floor(Math.random() * 999999) + 100000),
      occupation: jobTitles[Math.floor(Math.random() * jobTitles.length)],
      company: 'TechCorp Solutions',
      department: departments[Math.floor(Math.random() * departments.length)],
      jobTitle: jobTitles[Math.floor(Math.random() * jobTitles.length)] + ' ' + departments[Math.floor(Math.random() * departments.length)],
      employeeId: `TC${String(i).padStart(3, '0')}`,
      joinDate: new Date(2020 + Math.floor(Math.random() * 4), Math.floor(Math.random() * 12), Math.floor(Math.random() * 28) + 1),
      salary: 600000 + Math.floor(Math.random() * 1500000),
      workType: ['Full-time', 'Part-time', 'Contract'][Math.floor(Math.random() * 3)],
      status: ['Active', 'Active', 'Active', 'On Leave'][Math.floor(Math.random() * 4)],
      skills: ['JavaScript, Python', 'Java, Spring', 'React, Node.js', 'SQL, Analytics', 'Communication, Leadership'][Math.floor(Math.random() * 5)],
      experience: Math.floor(Math.random() * 15) + 1,
      education: ['B.Tech', 'M.Tech', 'MBA', 'B.Sc', 'M.Sc'][Math.floor(Math.random() * 5)],
      certifications: ['AWS Certified', 'PMP', 'Agile', 'Scrum Master', 'None'][Math.floor(Math.random() * 5)],
      emergencyContact: `${firstName} ${lastName} Sr.`,
      emergencyPhone: `+91-987654${String(4230 + i).padStart(4, '0')}`,
      relationship: ['Father', 'Mother', 'Spouse', 'Sibling'][Math.floor(Math.random() * 4)],
      bloodGroup: ['A+', 'B+', 'O+', 'AB+'][Math.floor(Math.random() * 4)],
      maritalStatus: ['Single', 'Married', 'Single', 'Married'][Math.floor(Math.random() * 4)],
      nationality: 'Indian',
      languages: 'English, Hindi',
      hobbies: ['Reading, Traveling', 'Gaming, Coding', 'Music, Dance', 'Sports, Fitness'][Math.floor(Math.random() * 4)],
      socialMedia: 'linkedin.com/in/' + firstName.toLowerCase() + lastName.toLowerCase(),
      notes: 'Team player with good communication skills',
      priority: ['Low', 'Medium', 'High'][Math.floor(Math.random() * 3)],
      assignedTo: `Manager ${String.fromCharCode(65 + Math.floor(Math.random() * 10))}`,
      dateAdded: new Date(2020 + Math.floor(Math.random() * 4), Math.floor(Math.random() * 12), Math.floor(Math.random() * 28) + 1)
    });
  }
  return moreUsers;
};

async function seedUserDatabase() {
  try {
    // Connect to MongoDB
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    // Clear existing user data
    await User.deleteMany({});
    console.log('Cleared existing users');

    // Combine sample users with generated users
    const allUsers = [...sampleUsers, ...generateMoreUsers()];
    
    // Insert user data
    const insertedUsers = await User.insertMany(allUsers);
    console.log(`Successfully inserted ${insertedUsers.length} users`);

    // Display statistics
    const total = await User.countDocuments();
    const today = new Date();
    const todayCount = await User.countDocuments({ 
      dateAdded: { 
        $gte: new Date(today.getFullYear(), today.getMonth(), today.getDate()) 
      } 
    });
    const lastWeek = new Date(today.getTime() - 7 * 24 * 60 * 60 * 1000);
    const lastWeekCount = await User.countDocuments({ dateAdded: { $gte: lastWeek } });
    const lastMonth = new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000);
    const lastMonthCount = await User.countDocuments({ dateAdded: { $gte: lastMonth } });

    console.log(`\nUser Database Statistics:`);
    console.log(`Total users: ${total}`);
    console.log(`Added today: ${todayCount}`);
    console.log(`Added this week: ${lastWeekCount}`);
    console.log(`Added this month: ${lastMonthCount}`);
    console.log(`Departments: ${[...new Set(allUsers.map(u => u.department))].join(', ')}`);
    console.log(`Status: ${[...new Set(allUsers.map(u => u.status))].join(', ')}`);

  } catch (error) {
    console.error('Error seeding user database:', error);
  } finally {
    mongoose.connection.close();
  }
}

seedUserDatabase();
